select top 3* from cars
select top 3* from sales
select top 3* from salespersons

--1. What are the details of all cars purchased in the year 2022?

select make,
       type,
	   style,
	   cost_$ 
from sales s left join cars c on s.car_id=c.car_id
where FORMAT(purchase_date,'yyyy')=2022

--2. What is the total number of cars sold by each salesperson?

select name,
       COUNT(c.car_id) [Total Cars Sold]
from salespersons ss left join sales s on ss.salesman_id=s.salesman_id
                     left join cars c on c.car_id=s.car_id
group by name


--3. What is the total revenue generated by each salesperson?

select name,
       SUM(cost_$) [Total Revenue]
from salespersons ss left join sales s on ss.salesman_id=s.salesman_id
                     left join cars c on c.car_id=s.sale_id
group by name

--4. What are the details of the cars sold by each salesperson?

select name,
       make,
	   type,
	   style,
	   cost_$ 
from salespersons ss left join sales s on ss.salesman_id=s.salesman_id
                     left join cars c on c.car_id=s.car_id


--5. What is the total revenue generated by each car type?

select type,
       (COUNT(s.car_id))*cost_$ [Total Revenue Generated]
from cars c left join sales s on s.car_id=c.car_id
group by type,cost_$


--6. What are the details of the cars sold in the year 2021 by salesperson 'Emily Wong'?

select make,
       type,
	   style,
	   cost_$ 
from cars c left join sales s on c.car_id=s.car_id
            left join salespersons ss on ss.salesman_id=s.salesman_id
where name='Emily Wong' and FORMAT(purchase_date,'yyyy')=2021


--7. What is the total revenue generated by the sales of hatchback cars?

select COUNT(s.car_id)*cost_$ [Total Sales]
from cars c left join sales s on c.car_id=s.car_id 
where style='Hatchback'
group by cost_$


--8. What is the total revenue generated by the sales of SUV cars in the year 2022?

select SUM([Total Sales])[Total Sales] from (
												select COUNT(s.car_id)*cost_$  [Total Sales]
												from cars c left join sales s on c.car_id=s.car_id
												where YEAR(purchase_date)=2022 and style='SUV'
												group by cost_$
											)s

--9. What is the name and city of the salesperson who sold the most number of cars in the year 2023?

select top 1name         
from salespersons ss left join sales s on ss.salesman_id=s.salesman_id 
where YEAR(purchase_date)=2023
group by name 
order by COUNT(sale_id) desc

--10. What is the name and age of the salesperson who generated the highest revenue in the year 2022?

select top 1 name--,COUNT(s.car_id)*cost_$ [Total Revenue]
from salespersons ss left join sales s on ss.salesman_id=s.salesman_id 
                     left join cars c on c.car_id=s.car_id
					 where YEAR(purchase_date)=2022
					 group by name,cost_$
					 order by COUNT(s.car_id)*cost_$ desc



					

						



